            <div class="row setup-content tab-pane" id="step-<?php echo $no; ?>">
                <div class="col-xs-12">
                    <div class="col-md-12">
                        <h3><?php echo CAT_Installer::lang()->t('Step') ?> <?php echo $no; ?>: <?php echo CAT_Installer::lang()->t('Database settings') ?></h3>
                        <div class="alert alert-info">
                            <?php echo CAT_Installer::lang()->t('The database you want to use must already be installed, and you must have a database admin user and password. If you are unsure what these terms mean you should probably contact your hosting provider.') ?>
                        </div>
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="db_hostname">Hostname</label>
                            <div class="col-sm-10">
                                <input type="text" name="db_hostname" id="db_hostname" required="required" class="input-sm form-control" value="<?php echo ( isset($data['db_hostname']) ? CAT_Installer::$data['db_hostname'] : 'localhost' ); ?>" />
                                <p class="help-block small with-errors"><?php echo CAT_Installer::lang()->t('The IP Address / host name where the database is available.') ?></p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="db_port">Port</label>
                            <div class="col-sm-10">
                                <input type="text" name="db_port" id="db_port" class="input-sm form-control" value="<?php echo ( isset(CAT_Installer::$data['db_port']) ? CAT_Installer::$data['db_port'] : '3306' ); ?>" />
                                <p class="help-block small with-errors"><?php echo CAT_Installer::lang()->t("Leave this as-is if you don't know what it is for. If you're using USBWebserver (Portable), set this to 3307.") ?></p>
                            </div>
                        </div>
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="db_name"><?php echo CAT_Installer::lang()->t('Database name') ?></label>
                            <div class="col-sm-10">
                                <input type="text" name="db_name" id="db_name" required="required" class="input-sm form-control" value="<?php echo ( isset(CAT_Installer::$data['db_name']) ? CAT_Installer::$data['db_name'] : '' ); ?>" />
                                <p class="help-block small with-errors"><?php echo CAT_Installer::lang()->t('The name of the database where the tables are created.') ?></p>
                            </div>
                        </div>
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="db_username"><?php echo CAT_Installer::lang()->t('Admin user') ?></label>
                            <div class="col-sm-10">
                                <input type="text" name="db_username" id="db_username" required="required" class="input-sm form-control" placeholder="Example: root" value="<?php echo ( isset(CAT_Installer::$data['db_username']) ? CAT_Installer::$data['db_username'] : '' ); ?>" />
                                <p class="help-block small with-errors"><?php echo CAT_Installer::lang()->t('An admin user that is allowed to create tables.') ?></p>
                            </div>
                        </div>
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="db_password"><?php echo CAT_Installer::lang()->t('Password') ?></label>
                            <div class="col-sm-10">
                                <input type="password" name="db_password" id="db_password" required="required" class="input-sm form-control" placeholder="*****" value="<?php echo ( isset(CAT_Installer::$data['db_password']) ? CAT_Installer::$data['db_password'] : '' ); ?>" />
                                <p class="help-block small with-errors"><?php echo CAT_Installer::lang()->t('The password of the admin user you entered above.') ?></p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="db_prefix"><?php echo CAT_Installer::lang()->t('Table prefix') ?></label>
                            <div class="col-sm-10">
                                <input type="text" name="db_prefix" id="db_prefix" required="required" class="input-sm form-control" placeholder="Example: cat_" value="<?php echo ( isset(CAT_Installer::$data['db_prefix']) ? CAT_Installer::$data['db_prefix'] : '' ); ?>" />
                                <p class="help-block small with-errors"><?php echo CAT_Installer::lang()->t('The prefix will be used to distinguish the BlackCat CMS table names from other tables that may already exist in the database.') ?></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>