        <ul class="progress-indicator">
            <?php foreach(CAT_Installer::$steps[CAT_Installer::$mode] as $i => $label): $i++;?>
            <li class="">
                <span class="bubble"></span> <?php echo CAT_Installer::lang()->t(ucfirst(str_replace('_',' ',$label))); ?>
            </li>
            <?php endforeach; ?>
        </ul>

        <div id="bar" class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"></div>
        </div>