            <div class="row setup-content tab-pane" id="step-<?php echo $no; ?>">
                <div class="col-xs-12">
                    <div class="col-md-12">
                        <h3><?php echo CAT_Installer::lang()->t('Step') ?> <?php echo $no; ?>: <?php echo CAT_Installer::lang()->t('Globals'); ?></h3>
                        <div class="alert alert-info col-md-offset-2 col-sm-10">
                            <?php echo CAT_Installer::lang()->t('All settings on this page can be changed in the admin backend later!') ?>
                        </div>
                        <div class="form-group required">
                            <label class="control-label col-sm-2">CMS URL</label>
                            <div class="col-sm-10">
                                <input type="url" name="base_url" id="base_url" required="required" class="input-sm form-control" value="<?php if(isset(CAT_Installer::$data['cms_url'])): echo CAT_Installer::$data['cms_url']; else: echo $base_url; endif; ?>" />
                                <p class="help-block"><?php echo CAT_Installer::lang()->t('This is the base URL of the CMS (=the directory where BlackCat CMS is installed). The base URL is used (=needed) to generate the correct URLs for Pages, CSS- and JavaScript inclusions, and so on.') ?></p>
                            </div>
                        </div>
                        <div class="form-group required">
                            <label class="control-label col-sm-2"><?php echo CAT_Installer::lang()->t('Website title') ?></label>
                            <div class="col-sm-10">
                                <input type="text" name="title" id="title" required="required" class="input-sm form-control" value="<?php if(isset(CAT_Installer::$data['title'])): echo CAT_Installer::$data['title']; else: echo 'BlackCat CMS'; endif; ?>" />
                                <p class="help-block"><?php echo CAT_Installer::lang()->t('You can set the &lt;title&gt; attribute indiviually for each page. This setting will be used as a default for pages that do not have an individual setting.') ?></p>
                            </div>
                        </div>
                        <div class="form-group required">
                            <label class="control-label col-sm-2"><?php echo CAT_Installer::lang()->t('Default Timezone') ?></label>
                            <div class="col-sm-10">
                                <select class="input-sm form-control">
                                <?php foreach(array_values(CAT_Installer::$data['timezone_table']) as $tz): ?>
                                    <option value="<?php echo $tz ?>"<?php if(isset(CAT_Installer::$data['default_timezone']) && CAT_Installer::$data['default_timezone'] == $tz): echo ' selected="selected"'; endif; ?>><?php echo $tz ?></option>
                                <?php endforeach; ?>
                                </select>
                                <p class="help-block"><?php echo CAT_Installer::lang()->t('The default timezone is used as presetting for new users, for example.') ?></p>
                            </div>
                        </div>
                        <?php if(CAT_Installer::$data['ssl_available']): ?>
                        <div class="form-group">
                            <label class="control-label col-sm-2"><?php echo CAT_Installer::lang()->t('Require SSL for the Admin Panel'); ?></label>
                            <div class="col-sm-10">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" value="yes" <?php if(isset(CAT_Installer::$data['ssl']) && CAT_Installer::$data['ssl']=='yes'): echo 'checked="checked"'; endif; ?> /> <?php echo CAT_Installer::lang()->t('Yes') ?>
                                    </label>
                                </div>
                                <p class="help-block"><?php echo CAT_Installer::lang()->t('The installer has detected that SSL (=https) seems to be available on this host. We recommend to require it for backend access. This means that the login page will switch to https automatically.'); ?></p>
                            </div>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>