      <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
          <div class="col-12 col-md">
            <small class="d-block mb-3 text-muted">&copy; <?php echo date('Y') ?> BlackCat Development</small>
          </div>
        </div>
      </footer>
    </div>
    <script src="<?php echo BASE_URL ?>/js/jquery-core.min.js"></script>
    <script src="<?php echo BASE_URL ?>/js/popper.min.js"></script>
    <script src="<?php echo BASE_URL ?>/js/bootstrap.min.js"></script>
    <script src="<?php echo BASE_URL ?>/js/progress.js"></script>
</body>
</html>