<head>
    <meta content="IE=edge" http-equiv="X-UA-Compatible" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title><?php include 'name.phtml'; ?> Installation Wizard</title>
    <link rel="stylesheet" href="<?php echo BASE_URL ?>/css/bootstrap.min.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="<?php echo BASE_URL ?>/css/progress-tracker.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="<?php echo BASE_URL ?>/css/style.css" type="text/css" media="screen" />
</head>
<body data-base-url="<?php echo BASE_URL ?>">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary border-bottom">
    <a class="navbar-brand" href="https://blackcat-cms.org"><?php include 'name.phtml'; ?> Installation</a>
    <?php if(isset($mode)): ?><span class="badge badge-info"><?php echo t($mode).' '.t('Mode') ?></span><?php endif; ?>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a class="nav-link" href="#">Features</a></li>
        <li class="nav-item"><a class="nav-link" href="#">Support</a></li>
      </ul>
    </div>
  </nav>

  <div class="container mt-4">