              <form id="proxy">
                <input type="hidden" name="proceed" value="1" />
                <div class="alert alert-secondary">
                    <?php echo $this->t('If you need a proxy to connect to the internet, ...') ?>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label"><?php echo $this->t('HTTP Proxy') ?></label>
                    <div class="col-sm-10">
                        <input aria-describedby="aproxyHelpBlock" type="text" name="proxy" id="proxy" class="form-control" placeholder="<?php echo $this->t('Example: http://proxy.yourdomain.com:8080'); ?>" />
                        <small id="aproxyHelpBlock" class="form-text text-muted"><?php echo $this->t("blablabla") ?></small>
                    </div>
                </div>
              </form>